In [5]:
import numpy as np
import sympy as sym
import math
import matplotlib.pyplot as plt

x = sym.symbols('x')

In [44]:
def f(x):
    return math.sin(x / 5) * math.exp(x / 10) + 5 * math.exp(-x / 2)

print(f(1.0))

3.25221686527


In [38]:
coord = [1.0,4.0,10.0,15.0]
size = len(coord)
# X = np.zeros((size,size))
# W = np.zeros((size,1))
# F = np.zeros((size,1))

def X_CREATE(x):
#     size = len(x)
    X = np.zeros((size,size))
    for i in range(X.shape[0]):
        for j in range(X.shape[1]):
            X[i][j] = x[i]**j
    return X

def F_CREATE(x1):
    F = np.zeros((size,1))
    for i in range(F.shape[0]):
        x_ = x1[i]
        F[i][0] = f(x_)
    return F
    
    
X1 = X_CREATE(coord)
F1 = F_CREATE(coord)
print(X1)
print(F1)

# numpy.linalg.solve(левая часть системы, правая часть системы)
W = np.linalg.solve(X1, F1)

print(W)

def check(x):
    return 2.94378905 -1.32450651*x**1 + 0.2303422*x**2 - 0.01022753*x**3

print check(15)

[[1.000e+00 1.000e+00 1.000e+00 1.000e+00]
 [1.000e+00 4.000e+00 1.600e+01 6.400e+01]
 [1.000e+00 1.000e+01 1.000e+02 1.000e+03]
 [1.000e+00 1.500e+01 2.250e+02 3.375e+03]]
[[3.25221687]
 [1.74684595]
 [2.50541641]
 [0.63522142]]
[[ 4.36264154]
 [-1.29552587]
 [ 0.19333685]
 [-0.00823565]]
0.38527265
