In [ ]:
?open

In [2]:
import re
import numpy as np

In [3]:
# построчно считываем файл
with open('sentences.txt', 'r') as f:
    files = f.read().splitlines()
print(files[0])

In comparison to dogs, cats have not undergone major changes during the domestication process.


In [4]:
# приводим строки к нижнему регистру
for i in range(len(files)):
    files[i]=files[i].lower()
print files

['in comparison to dogs, cats have not undergone major changes during the domestication process.', 'as cat simply catenates streams of bytes, it can be also used to concatenate binary files, where it will just concatenate sequence of bytes.', 'a common interactive use of cat for a single file is to output the content of a file to standard output.', 'cats can hear sounds too faint or too high in frequency for human ears, such as those made by mice and other small animals.', 'in one, people deliberately tamed cats in a process of artificial selection, as they were useful predators of vermin.', 'the domesticated cat and its closest wild ancestor are both diploid organisms that possess 38 chromosomes and roughly 20,000 genes.', 'domestic cats are similar in size to the other members of the genus felis, typically weighing between 4 and 5 kg (8.8 and 11.0 lb).', 'however, if the output is piped or redirected, cat is unnecessary.', 'cat with one named file is safer where human error is a conc

In [5]:
# делим строки на слова и выбрасываем пустые слова, создаем словарь

line_counter = 0
words = dict()
wcount = 0

for line in files:

    s = line
    tokens = re.split('[^a-z]',s)
    tokens = filter(None, tokens)
#     print tokens
    
    for j in range(len(tokens)):
        if tokens[j] not in words:
            words[tokens[j]] = wcount
#             M[line_counter][wcount] += 1
            wcount +=1
        else:
#             s = words.get[tokens[j]]
#             M[line_counter][s] += 1
            continue

print words
# print M
# words.get("comparison")
    

{'displays': 155, 'osx': 192, 'selection': 67, 'safari': 221, 'just': 31, 'developed': 194, 'over': 170, 'vermin': 72, 'domestic': 87, 'named': 104, 'installed': 181, 'symbols': 149, 'through': 206, 'human': 51, 'world': 142, 'disk': 244, 'its': 74, 'fifth': 249, 'features': 251, 'tamed': 65, 'upgrade': 232, 'lb': 97, 'drive': 248, 'to': 2, 'won': 239, 'deliberately': 64, 'marks': 226, 'has': 129, 'predecessor': 172, 'non': 199, 'which': 182, 'read': 122, 'october': 160, 'every': 215, 'os': 174, 'they': 68, 'not': 6, 'during': 10, 'now': 195, 'possess': 83, 'intel': 189, 'keyboards': 116, 'bytes': 20, 'unnecessary': 102, 'patch': 217, 'predators': 71, 'small': 60, 'output': 41, 'entirely': 235, 'where': 29, 'ears': 52, 'available': 164, 'on': 115, 'often': 113, 'sequence': 32, 'some': 177, 'lion': 202, 'frequency': 50, 'are': 78, 'year': 216, 'download': 205, 'terms': 123, 'concern': 107, 'error': 106, 'for': 37, 'pipes': 128, 'since': 187, 'factory': 180, 'artificial': 66, 'content': 

In [6]:
# проходим в цикле сроки, в каждой строке проходим в цикле слова и сверяем, какому индексу соответствует слово
line_counter = 0
M = np.zeros((22,254))
for line in files:
    s = line
    tokens = re.split('[^a-z]',s)
    tokens = filter(None, tokens)

    for j in range(len(tokens)):
#  сверяем, какому индексу соответствует слово
        index = int(words.get(tokens[j]))
#  в ячейку соответствующую текущей строке и индексу слова в словаре добавляем 1
        M[line_counter][index] += 1
    line_counter += 1

print M.shape
# print M[0]
print M

(22, 254)
[[1. 1. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 2. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 1. 1. 1.]]


In [8]:
from scipy.spatial import distance
print M
# .shape[0] - дает число строк, .shape[1] - колонок 
dist = np.zeros(M.shape[0])
print dist

for i in range(M.shape[0]):
    m = i
    dist[i] = distance.cosine(M[0],M[m])
    print i,"значение", dist[i]




[[1. 1. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 2. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 1. 1. 1.]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0 значение 0.0
1 значение 0.9527544408738466
2 значение 0.8644738145642124
3 значение 0.8951715163278082
4 значение 0.7770887149698589
5 значение 0.9402385695332803
6 значение 0.7327387580875756
7 значение 0.9258750683338899
8 значение 0.8842724875284311
9 значение 0.9055088817476932
10 значение 0.8328165362273942
11 значение 0.8804771390665607
12 значение 0.8396432548525454
13 значение 0.8703592552895671
14 значение 0.8740118423302576
15 значение 0.9442721787424647
16 значение 0.8406361854220809
17 значение 0.956644501523794
18 значение 0.9442721787424647
19 значение 0.8885443574849294
20 значение 0.8427572744917122
21 значение 0.8250364469440588


In [ ]:
6,21